version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"    # HTTP
      - "7687:7687"    # Bolt
    volumes:
      - ./neo4j_data:/data:z
      - ./neo4j_logs:/logs:z
      - ./neo4j_import:/var/lib/neo4j/import:z
      - ./neo4j_plugins:/plugins:z
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7474/browser/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local 